### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by roughani** [code4sac/codeforsacramento.org#26]
We ditched the Code4Sac branding in favor of Code for Sacramento or Code for Sac early last year. May not seem like a big deal, but it's really bad that we get written up in news articles with inconsistent branding and then the inconsistency affects our SEO. For example, as a citizen I don't know if I should Google "Code4Sac" or "Code 4 Sacramento" or "Code 4 Sac". This also affects how people send us emails with our Google Apps running on codeforsacramento.org. "For" is a more elegant brand because it's semantic and reflects proper use of the English language. 

Our best case is to ask @merittthomas (cc @efletch) to just replace the "4" our current logo with "for". However, if that's not feasible, we'll need a new logo.

**Comment by duanewilson** [comment]
![codeforsac](https://cloud.githubusercontent.com/assets/1859378/21919129/e908a338-d90c-11e6-9621-473f34f5592c.png)

Thoughts? Likes/Dislikes? Dropped the "4" in favor of "for" as that is the domain...

**Comment by joelrip** [comment]
Thanks @duanewilson ! I recently reached out to @merittthomas through another channel on this as well. Will add these to our list of options!

**Comment by feydan** [comment]
Our logo has since been updated.
