### ISSUE TITLE
www redirects to unsecured http site

### ISSUE THREAD

**Issue by natebass** [code4sac/codeforsacramento.org#97]
When you navigate to https://www.codeforsacramento.org it redirects to http://codeforsacramento.org.

**Comment by natebass** [comment]
We can compare behavior to openbudgetsac.org, which always redirects to the naked https domain.
### Open Budget Sac
**✅ Redirects to https**
https://www.openbudgetsac.org → https://openbudgetsac.org/
**✅ Redirects to https**
http://openbudgetsac.org → https://openbudgetsac.org/

### Code for Sacramento
**✅ Supports https**
https://codeforsacramento.org → https://codeforsacramento.org/
**❌ Redirects to http **
https://www.codeforsacramento.org → http://codeforsacramento.org/
**❌ Stays on http **
http://codeforsacramento.org → http://codeforsacramento.org/

This is despite the fact that both use GitHub pages and they have the same settings, from what I can see. The [Open Budget Sac CNAME](https://github.com/code4sac/openbudgetsac.org/blob/release-eleventy/CNAME) and [Code for Sacramento CNAME](https://github.com/code4sac/codeforsacramento.org/blob/gh-pages/CNAME) both list only the naked domain. The GitHub Pages settings are also are the same, only specifying the naked domain name.

![code-for-sac-pages-settings](https://github.com/code4sac/codeforsacramento.org/assets/6665595/b80f1b48-1ef9-4725-b91e-883bd853e2a9)
![open-budget-sac-pages-settings](https://github.com/code4sac/codeforsacramento.org/assets/6665595/02d87c96-fc1d-455b-88c3-753f8fc67161)

**Comment by MonstersInc-sudo** [comment]
I would try this potential fix since Certbot will likely be too much work.

https://stackoverflow.com/questions/54817253/github-pages-https-www-redirect

May be as simple as refetching the cert.

**Comment by natebass** [comment]
@MonstersInc-sudo I switched the setting to www.codeforsacramento.org, waited 5 minutes, and then switched it back to codeforsacramento.org. It looks like the issue is resolved on my Windows computer.

I'm going to leave the issue open for a bit and make sure we don't see the issue on any other machines. But it looks like it is resolved!

**Comment by natebass** [comment]
I checked on multiple computers and it is working.

**Comment by natebass** [comment]
The issue persisted in Edge on Windows after it was working on Chrome and Android.

To fix this, I typed edge://net-internals/#dns in the search bar in Edge. On the resulting page, press the "Clear host cache" button.

Other possible steps include running `ipconfig /flushdns` in PowerShell and pressing Ctrl+F5 on the website in question.
